spring:  profiles:    active:    - consul-consume1# feign hystrix 启用feign:  hystrix:    enabled: true---spring:  profiles: consul-consume1
server:
  port: 3001---spring:  profiles: consul-consume2server:  port: 3002