server:
  port: 4001
  
spring:
  rabbitmq:    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:    stream:      bindings:        output:
          destination: myExchange
          content-type: application/json
